### ISSUE TITLE
Error when starting exe createt via pyinstaller | ModuleNotFoundError: No module named 'jaraco.clipboard.Windows'

### ISSUE THREAD

**Issue by Tecki2015** [jaraco/jaraco.clipboard#12]
The python script itself works without issue.
Pyinstaller runs without errors but:
When i try to start the exe file i get the following error:

Traceback (most recent call last):
  File "html to markdown.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "jaraco\clipboard\__init__.py", line 27, in <module>
  File "jaraco\clipboard\__init__.py", line 12, in _init
  File "importlib\__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'jaraco.clipboard.Windows'

Line 1 in the script is: import jaraco.clipboard as clipboard
Operating System Win10 

Installed Libs:

Package                   Version
------------------------- ---------
altgraph                  0.17.3
autocommand               2.2.2
beautifulsoup4            4.12.2
html2text                 2020.1.16
inflect                   6.0.4
jaraco.classes            3.2.3
jaraco.clipboard          3.1.0
jaraco.collections        4.1.0
jaraco.context            4.3.0
jaraco.functools          3.6.0
jaraco.structures         2.1.0
jaraco.text               3.11.1
jaraco.ui                 2.3.0
jaraco.windows            5.7.0
keyboard                  0.13.5
Markdown                  3.4.3
markdownify               0.11.6
more-itertools            9.1.0
path                      16.6.0
pefile                    2023.2.7
Pillow                    9.5.0
pip                       23.0.1
pydantic                  1.10.7
pyinstaller               5.10.0
pyinstaller-hooks-contrib 2023.2
pystray                   0.19.4
pywin32-ctypes            0.2.0
setuptools                58.1.0
six                       1.16.0
soupsieve                 2.4
typing_extensions         4.5.0

**Comment by Tecki2015** [comment]
Solution: pyinstaller --onefile --noconsole --collect-submodules jaraco.clipboard.Windows
